# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 04:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170117_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='github_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='downsides',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='upsides',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 4, 15, 2, 279227, tzinfo=utc)),
        ),
    ]
