# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 04:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170118_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 4, 16, 22, 722749, tzinfo=utc)),
        ),
    ]
