# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170118_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='live_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 4, 38, 30, 934414, tzinfo=utc)),
        ),
    ]
