# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20170118_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 5, 54, 47, 897913, tzinfo=utc)),
        ),
    ]
