# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 04:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20170118_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 4, 19, 43, 731016, tzinfo=utc)),
        ),
    ]
