# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170119_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 4, 34, 55, 229676, tzinfo=utc)),
        ),
    ]
