# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20170122_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 22, 18, 47, 44, 294036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='live_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
