# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170226_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 26, 18, 58, 21, 893551, tzinfo=utc)),
        ),
    ]
