# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20170520_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 25, 2, 9, 8, 554127, tzinfo=utc)),
        ),
    ]
