# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20170525_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 25, 19, 10, 43, 126253, tzinfo=utc)),
        ),
    ]
