# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('device', models.CharField(choices=[('tablet', 'tablet'), ('phone', 'phone'), ('laptop', 'laptop'), ('desktop', 'desktop'), ('other', 'other')], max_length=100)),
                ('location', models.CharField(choices=[('bathroom', 'bathroom'), ('bedroom', 'bedroom'), ('other', 'other')], max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
