# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0002_auto_20170525_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 5, 25, 21, 33, 48, 254096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='datetime',
            field=models.DateField(),
        ),
    ]
