# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0003_auto_20170525_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 5, 25, 22, 55, 42, 281754, tzinfo=utc)),
        ),
    ]
