# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0004_auto_20170525_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 14, 21, 31, 15, 14030, tzinfo=utc)),
        ),
    ]
