# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
