# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('steam_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_playtime', models.IntegerField()),
                ('start_date', models.DateField()),
                ('time_limit', models.IntegerField()),
                ('current_playtime', models.IntegerField()),
                ('notified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
