# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170520_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackers',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 25, 2, 9, 8, 575297, tzinfo=utc)),
        ),
    ]
